apiVersion: v1
kind: Service
metadata:
  name: send
  
spec:
  selector:
    matchLabels:
      app: second-app
    
  ports:
  - protocols: 'TCP' 
    port: 80
    targetPort: 8080
    
  type: LoadBalancer
